Enabled tests suite again

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -49,16 +49,16 @@ jobs:
       - name: Build
         run: dotnet build --no-restore --configuration Release
 
-      # - name: Test
-      #   run: dotnet test --no-build --no-restore --configuration Release --logger "trx;LogFileName=TestResults.trx"
+      - name: Test
+        run: dotnet test --no-build --no-restore --configuration Release --logger "trx;LogFileName=TestResults.trx"
 
-      # - name: Test Report
-      #   uses: dorny/test-reporter@v1
-      #   if: success() || failure()    # run this step even if previous step failed
-      #   with:
-      #     name: Tests             # Name of the check run which will be created
-      #     path: "**/*.trx"        # Path to test results
-      #     reporter: dotnet-trx    # Format of test results
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Tests             # Name of the check run which will be created
+          path: "**/*.trx"        # Path to test results
+          reporter: dotnet-trx    # Format of test results
 
       - name: Login to Octopus Deploy 
         uses: OctopusDeploy/login@v0
